
apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: wyzDeployService
  annotations:
    alauda.io/displayName.zh-CN: wyz更新服务
    alauda.io/displayName.en: Update service
    alauda.io/description.zh-CN: 更新服务
    alauda.io/description.en: Update a service
    alauda.io/readme.zh-CN: 更新服务
    alauda.io/readme.en: Update a service
    alauda.io/version: v0.3
    alauda.io/style.icon: 
  labels:
    catgory: CD
spec:
  engine: graph
  withSCM: false
  stages:
    - name: DeployService
      tasks:
        - name: DeployService
          type: public/alaudaDeployService
          options:
            timeout: 3600
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: command
          schema:
            type: string
          binding:
            - DeployService.args.command
          display:
            type: string
            name:
              zh-CN: "接入点"
              en: "Entrypoint"
          required: false
        - name: timeout
          schema:
            type: int
          binding:
            - DeployService.args.timeout
          display:
            type: int
            name:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
          required: true
